on:
  schedule:
    - cron: "0 12 */1 * *"
jobs:
  az-repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: wowsr-repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/masterking32/WoWSimpleRegistration.git"
        source_branch: "master"
        destination_repo: "https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/WoWSimpleRegistration.git"
        destination_branch: "master"
  dev-stg-repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: dev-stg-repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/${{ secrets.GH_USERNAME }}/WoWSimpleRegistration.git"
        source_branch: "master"
        destination_repo: "https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/WoWSimpleRegistration.git"
        destination_branch: "dev-staging"
